"""add setup.agent provenance column

Revision ID: ee1b1d03e9a7
Revises: 
Create Date: 2026-07-03 15:28:56.868471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee1b1d03e9a7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Server default backfills existing rows to 'claude-code' before the
    # NOT NULL constraint is applied; SQLite/Postgres both honor this.
    op.add_column('setup', sa.Column('agent', sa.String(length=40),
                                     nullable=False, server_default='claude-code'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('setup', 'agent')
    # ### end Alembic commands ###
